---
.gitlab-ci.yml:
  delete: true

.project:
  delete: true

.travis.yml:
  branches:
    - develop
  includes:
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
      stage: spec

appveyor.yml:
  delete: true

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true

spec/spec_helper_acceptance.rb:
  unmanaged: false
